### ISSUE TITLE
Registering handlers manually

### ISSUE THREAD

**Issue by msvitlica** [Shuttle/Shuttle.Esb#11]
Hi, 
i was wondering is there any way i can manually register message handlers instead of automatically registering them from assembly ?

var handler = new CustomMessageHandler();
something like _serviceBus.RegisterHandler(handler) ?

Best regards,
Milan

**Comment by eben-roux** [comment]
Hi Milan,

The current interfaces do not allow for that, no.  However, you *could* implement your own message handler factory by deriving from `MessageHandlerFactory` and then having a publicly accessible method to register the handler type.  It wouldn't be a specific instance but rather a type.

The inbox pipeline request a message handler instance from the `given IMessageHandlerFactory` implementation based on the message type.  You could then have something like this:

```
var myFactory = new MyFactory();

myFactory.RegisterHandler(messageType, handlerType); // or just handlerType if the message type is determined from the generic

_bus = ServiceBus.Create(
				c => c.MessageHandlerFactory(myFactory)
				).Start();
```

Can you expand on your particular use-case?  I'd like to understand *why* you would like to do what you are trying to do :)

Regards,
Eben

**Comment by msvitlica** [comment]
Thank you for providing answer.

Regarding particular use-case, well, I'm kind of used to do it on that with MassTransit.

My main concern is that something will happen in backgrond (e.g. some unfinished or test handler will be registered in production or something) and that we will not notice.
With expicit registration of handlers, I can see on one place (app initializaiton code) all handlers by particular application or service. 
Correct me if I'm wrong but if I subscribe to message type rather than handler instance, there can be several handlers in background for the same type ? 
I may be completely wrong, since I've just got introduced in Shuttle source code, and started exploring it.

**Comment by eben-roux** [comment]
Interesting to see how others are doing this :)

Well, the test handlers would / should be in a test assembly of sorts.  But then again, typically you could test you *actual* handlers and pass in mocks.

However, if you want to explicitly register the handler types it certainly *is* possible.  However, in most cases one would want to employ a dependency container of sorts and *that* is where you could use one of the already implemented container types or create a new one for any container not yet supported.

There should be only one `IMessageHandler<T>` per type `T` in the assembly.  Currently I think most implementations will not fail but they'll only use the first one found.

I guess there are pros and cons either way.  For the most part you would want to register all handlers for message types processed by an endpoint.

However, event subscriptions *are* explicit.  So any endpoint interested in an event message would need to subscribe.  Well, the subscription *can* be set up manually the in the subscription store but having it in the endpoint ensures that the subscription exists since, typically, you would have a read-only user for the subscription store in production (so it won't register but fail if the subscription does not exist).

The explicit registration *has* come up before so it may be worth investigating an explicit registration `IMessageHandlerFactory` implementation.

Do you use a DI container?

Let me know what you think?

**Comment by msvitlica** [comment]
I'm not using DI container on this use-case.

To me implementing `IMessageHandlerFactory` seems reasonable solution at this point, so if we pick Shuttle for our application, we will probably do it.
Sql server implementation is what we need, because of some very specific requirements in production envrionment.

**Comment by eben-roux** [comment]
Ah, ok :)

Please do let me know if you need help with anything.  If you could get away with the auto-registration it would be first prize.

Keep in mind that the startup pipeline attempts an optional initialization on the `MessageHandlerFactory` and then calls the `RegisterHandlers()` method.  In your case you *could* register some usual suspects.  There is an internal handler `public class WorkerAvailableHandler : IMessageHandler<WorkerThreadAvailableCommand>` that is also automatically registered.  This is used by an endpoint set up as a distributor so if you need to distribute message you should remember to register that handler also.

But as I said, if you run into any issues please let me know :)

And thanks for taking a look at Shuttle

**Comment by msvitlica** [comment]
You are welcome and thank you for promt responses.
