### ISSUE TITLE
Autofac support... message handler factory

### ISSUE THREAD

**Issue by claytona-armstrong5** [Shuttle/Shuttle.Esb#26]
We are trying to use the new Autofac support that was recently introduced, but have been unable to locate the message handler factory to make it work.  
For Windsor this is in the library called "Shuttle.Esb.Castle" (separate from "Shuttle.Core.Castle").
But there does not seem to be a corresponding library for Autofac.

Probably more of a question than an issue... is there a message handler factory for Autofac?

thanks!

**Comment by claytona-armstrong5** [comment]
Sorry, please ignore.

I eventually realised the message handler factory is no longer required.

**Comment by eben-roux** [comment]
Glad that you got it sorted.  It can be somewhat confusing with the latest version since the DI wiring has changed quite a bit and the containers being moved to the Shuttle.Core namespace.  I was finding that I was duplicating functionality across Shuttle.Esb and Shuttle.Recall and decided to do the change.  I hope it was for the better.

**Comment by claytona-armstrong5** [comment]
Yes, I've noticed there's been a lot of change... it's great that you are still doing big refactors, that's what will keep it improving. 
Many thanks again for the great work you do on this

**Comment by eben-roux** [comment]
Released:

- nuget: https://www.nuget.org/packages/Shuttle.Core.Autofac/
- repository: https://github.com/Shuttle/Shuttle.Core.Autofac
