### ISSUE TITLE
UnrecoverableHandlerExceptions dont go straight to the error queue

### ISSUE THREAD

**Issue by andyhracti** [Shuttle/Shuttle.Esb#40]
Hi , 
We're trying to send a message straight to the error queue by raising an 'UnrecoverableHandlerException'.

Currently using  Shuttle.ESB 10.1.0, ESB.SQL.Queue/Subscription 10.1.2. 

When we raise the exception, messages are going back to the defer queue rather than the erorr queue. This is doing the same when using an SQL based queue and does a similar thing when using the 'Defer Demo' and thowing the exception in the handler there.  The messages just get deferred

**Comment by eben-roux** [comment]
Yip, most definitely a bug...

The original exception (UnrecoverableHandlerException) is wrapped so the comparison fails.  Will need to add a test for that.

I'll get to this as soon as I can.

**Comment by eben-roux** [comment]
I have released https://github.com/Shuttle/Shuttle.Esb/releases/tag/v10.1.1

If `Shuttle.Esb` is referenced as a dependency from one of the other packages such as `Shuttle.Esb.Sql.Queue` you may need to reference it directly in order to get to the latest version; else the  dependent one is used which may be an earlier version.  Quite an odd affair with Nuget in that case.

Please let me know if that sorted the issue.

**Comment by andyhracti** [comment]
Hi Eben, 
No problems updating via nuget here, and fixes the bug.
Thanks

**Comment by eben-roux** [comment]
Please re-open or log another issue should this still present a problem.
